git submodule add https://github.com/ControleOnline/ui-common.git modules/controleonline/ui-common
git submodule add https://github.com/ControleOnline/ui-default.git modules/controleonline/ui-default
git submodule add https://github.com/ControleOnline/ui-login.git modules/controleonline/ui-login
git submodule add https://github.com/ControleOnline/ui-users.git modules/controleonline/ui-users
git submodule add https://github.com/ControleOnline/ui-tasks.git modules/controleonline/ui-tasks
git submodule add https://github.com/ControleOnline/ui-products.git modules/controleonline/ui-products
git submodule add https://github.com/ControleOnline/ui-people.git modules/controleonline/ui-people
git submodule add https://github.com/ControleOnline/ui-financial.git modules/controleonline/ui-financial
git submodule add https://github.com/ControleOnline/ui-providers.git modules/controleonline/ui-providers
git submodule add https://github.com/ControleOnline/ui-professionals.git modules/controleonline/ui-professionals
git submodule add https://github.com/ControleOnline/ui-logistic.git modules/controleonline/ui-logistic
git submodule add https://github.com/ControleOnline/ui-carrier.git modules/controleonline/ui-carrier
git submodule add https://github.com/ControleOnline/ui-customers.git modules/controleonline/ui-customers
git submodule add https://github.com/ControleOnline/ui-crm.git modules/controleonline/ui-crm
git submodule add https://github.com/ControleOnline/ui-layout.git modules/controleonline/ui-layout
git submodule add https://github.com/ControleOnline/ui-employee.git modules/controleonline/ui-employee
git submodule add https://github.com/ControleOnline/ui-shop.git modules/controleonline/ui-shop
git submodule add https://github.com/ControleOnline/ui-legacy.git modules/controleonline/ui-legacy
git submodule add https://github.com/ControleOnline/ui-contracts.git modules/controleonline/ui-contracts
git submodule add https://github.com/ControleOnline/ui-accounting.git modules/controleonline/ui-accounting
git submodule add https://github.com/ControleOnline/ui-dashboard.git modules/controleonline/ui-dashboard
git submodule add https://github.com/ControleOnline/ui-config.git modules/controleonline/ui-config
git submodule add https://github.com/ControleOnline/ui-delivery.git modules/controleonline/ui-delivery
git submodule add https://github.com/ControleOnline/ui-docs.git modules/controleonline/ui-docs
git submodule add https://github.com/ControleOnline/ui-ead.git modules/controleonline/ui-ead
git submodule add https://github.com/ControleOnline/ui-guides.git modules/controleonline/ui-guides
git submodule add https://github.com/ControleOnline/ui-import.git modules/controleonline/ui-import
git submodule add https://github.com/ControleOnline/ui-support.git modules/controleonline/ui-support
git submodule add https://github.com/ControleOnline/ui-orders.git modules/controleonline/ui-orders
git submodule add https://github.com/ControleOnline/ui-translate.git modules/controleonline/ui-translate
git submodule add https://github.com/ControleOnline/ui-pcp.git modules/controleonline/ui-pcp
