name: Deploy Project
on:
  push:
    branches: [production]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Creating Config
        run: |
          echo "const env = {\
          API_ENTRYPOINT: 'https://api.controleonline.com',\
          APP_TYPE: 'ERP',\
          ZOOM: 0.80,\
          OAUTH_GOOGLE_CLIENT_ID:'${{ secrets.OAUTH_GOOGLE_CLIENT_ID }}',\
          GMAPS_GOOGLE_CLIENT_ID:'${{ secrets.GMAPS_GOOGLE_CLIENT_ID }}',\
          NEW_RELIC:{\
            LICENSE_KEY:'${{ secrets.NEW_RELIC_LICENSE_KEY }}',\
            APPLICATION_ID:'${{ secrets.NEW_RELIC_APPLICATION_ID }}',\
            ACCOUNT_ID: '${{ secrets.NEW_RELIC_ACCOUNT_ID }}',\
            TRUST_KEY: '${{ secrets.NEW_RELIC_TRUST_KEY }}',\
            BEACON: '${{ secrets.NEW_RELIC_BEACON }}',\
            ERROR_BEACON: '${{ secrets.NEW_RELIC_ERROR_BEACON }}'\
          }\
          };\
          module.exports = { env };\
          " > ./config/env.local.js
      - name: Update Submodules
        run: |
          git submodule update --recursive --init
          git submodule update --recursive --remote
      - name: Install Modules
        run: |
          npm install --global yarn
          yarn
      - name: Build
        run: |
          npx quasar build -m spa
      - name: Deploy
        uses: locaweb/ftp-deploy@1.0.0
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          localDir: "./dist/spa"
          remoteDir: "~/public_html"
          forceSsl: false
